import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import S from '../layout.module.scss';
import '../globals.scss';
import Cursor from '../components/cursor/Cursor';
import SmoothScrollW from '../components/wrappers/SmoothScrollW';
import Blocks from '../components/blocks/Blocks';
import Header from '../components/header/Header';

const font = Poppins({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <SmoothScrollW>
        <body className={`${font.className} ${S.body}`}>
          <Blocks />
          <Header />
          {children}
          <Cursor />
        </body>
      </SmoothScrollW>
    </html>
  );
}
